### ISSUE TITLE
missing exposedPorts name when getting a resource

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#16]
create a job,
get a job,

the following occurs:
response is 
            "exposedPorts": [
                {
                    "name": "",
                    "port": 1,
                    "protocol": "udp"
                }
            ]
        }

the name is a blank string.

**Comment by tanxu-zdns** [comment]
cronjob has the same issue

**Comment by zdnsjoe** [comment]
fixed

**Comment by tanxu-zdns** [comment]
still present
on

deployment
daemonset
statefulset
job
cronjob

**Comment by zdnsjoe** [comment]
no reproduce
